server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    ## 等待队列长度，默认100。
    #accept-count: 1000
    ## 超时最多5秒后断开连接
    connection-timeout: 5000
    threads:
      ## 最大工作线程数，默认200 （
      max: 800
      ## 最小工作空闲线程数，默认10
      min-spare: 100

spring:
  main:
    allow-bean-definition-overriding: true
  http:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: courage
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.100.115.11:3306/scoreplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 47.100.115.11
    port: 6379
    password: root
    timeout: 60000 #连接超时时间（毫秒）
    lettuce:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 1   # 连接池中的最小空闲连接


logging:
  config: classpath:logback.xml

common:
  mapServer:
    mapApiUrl: http://api.map.baidu.com
    mapApiAk: 133848c89004afe8dede89ef7428c98d
  fileTEMP:
    tmpFilePath: /tmpfile
# management.endpoints.web.exposure.include: '*'
